language: ruby
rvm:
  - "2.1.2"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database concert_management_test;' -U postgres
  - npm install karma
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - karma start --single-run --browsers PhantomJS test/karma/config/unit.js